version: '3'
    
services:

    elasticsearch:
        image: elasticsearch:7.8.1
        environment:
            - discovery.type=single-node
        ports:
        - "9200:9200"
    
    platform:
        build: .
        command: python src/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on: 
            - elasticsearch
