version: '3'
    
services:

    elasticsearch:
        build: elasticsearch/
        ports:
        - 9200:9200
        - 9300:9300
        environment: 
        - discovery.type=single-node
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - transport.host=127.0.0.1
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - http.host=0.0.0.0
        - http.port=9200
        - "http.cors.allow-origin=http://localhost:3000"
        - "http.cors.enabled=true"
        - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
        - "http.cors.allow-credentials=true"
        container_name: elasticsearch

    kibana:
        build: kibana/
        ports:
        - 5601:5601
        depends_on:
        - elasticsearch
        container_name: kibana

    platform:
        build: src/
        command: bash -c "python src/manage.py makemigrations && python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code/src
        ports:
            - "8000:8000"
        depends_on: 
            - elasticsearch
    
    web:
        build: ./web
        tty: true
        command: npm start --silent
        volumes:
            - ./web:/code/web
            - /web/node_modules
        ports:
        - "3000:3000"
        container_name: web
        depends_on: 
            - platform
