version: '3'
    
services:

    elasticsearch:
        image: elasticsearch:7.8.1
        environment:
            - discovery.type=single-node
        ports:
        - "9200:9200"

    kibana:
        labels:
            com.example.service: "kibana"
            com.example.description: "Data visualisation and for log aggregation"
        image: kibana:7.8.1
        container_name: kibana
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_URL=http://localhost:9200
        depends_on:
            - elasticsearch   

    platform:
        build: .
        command: bash -c "python src/manage.py makemigrations && python src/manage.py migrate && python src/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on: 
            - elasticsearch
    
    web:
        build: ./web
        tty: true
        command: npm start --silent
        volumes:
            - ./web:/code/web
        ports:
            - "3000:3000"